"""Local media storage for post image attachments.

Safety properties
-----------------
* The stored file name is generated by the server; a user's filename is kept only
  as untrusted metadata and is never used as a path.
* The content type is derived from the file's magic bytes, not from the request
  header, and must be on the configured allow-list. SVG and other active markup
  formats are therefore rejected.
* Downloads are always re-served from disk with the sniffed content type and
  ``Content-Disposition: inline`` plus a restrictive CSP, never as HTML.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass
from pathlib import Path

from .security import sha256_hex


@dataclass(frozen=True)
class StoredObject:
    storage_key: str
    content_type: str
    byte_size: int
    sha256: str
    path: Path


class MediaError(ValueError):
    pass


def sniff_image_type(data: bytes) -> str | None:
    """Return the content type implied by the file signature, else ``None``."""
    if len(data) < 12:
        return None
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if data.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if data.startswith(b"GIF87a") or data.startswith(b"GIF89a"):
        return "image/gif"
    if data[0:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "image/webp"
    return None


EXTENSIONS = {
    "image/png": "png",
    "image/jpeg": "jpg",
    "image/gif": "gif",
    "image/webp": "webp",
}


class MediaStore:
    def __init__(self, config):
        self.config = config
        self.root = Path(config.media_root)
        self.root.mkdir(parents=True, exist_ok=True)

    # ---- validation -----------------------------------------------------------
    def validate_upload(self, data: bytes, filename: str | None = None) -> str:
        """Validate an upload and return the trusted content type."""
        if not data:
            raise MediaError("That file is empty.")
        if len(data) > self.config.max_upload_bytes:
            limit_mb = self.config.max_upload_bytes / (1024 * 1024)
            raise MediaError(f"Images must be {limit_mb:.1f} MB or smaller.")
        detected = sniff_image_type(data)
        if detected is None:
            raise MediaError("Upload a PNG, JPEG, GIF or WebP image.")
        if detected not in self.config.allowed_image_types:
            raise MediaError("That image format is not accepted on this instance.")
        if filename and len(filename) > 200:
            filename = filename[:200]
        return detected

    # ---- storage --------------------------------------------------------------
    def save(self, data: bytes, content_type: str, *, subdir: str = "posts") -> StoredObject:
        extension = EXTENSIONS.get(content_type, "bin")
        key = f"{subdir}/{secrets.token_hex(16)}.{extension}"
        path = self.root / key
        path.parent.mkdir(parents=True, exist_ok=True)
        temp = path.with_suffix(path.suffix + ".part")
        with temp.open("wb") as handle:
            handle.write(data)
        temp.replace(path)
        return StoredObject(
            storage_key=key,
            content_type=content_type,
            byte_size=len(data),
            sha256=sha256_hex(data),
            path=path,
        )

    def path_for(self, storage_key: str) -> Path:
        """Resolve a storage key, refusing anything that escapes the media root."""
        root = self.root.resolve()
        candidate = (self.root / storage_key).resolve()
        if not str(candidate).startswith(str(root)) or not candidate.is_file():
            raise MediaError("Media object not found.")
        return candidate

    def read(self, storage_key: str) -> bytes:
        return self.path_for(storage_key).read_bytes()

    def delete(self, storage_key: str) -> bool:
        try:
            path = self.path_for(storage_key)
        except MediaError:
            return False
        try:
            path.unlink()
        except OSError:
            return False
        return True
